### ISSUE TITLE
Question about mhp2g .mib files 

### ISSUE THREAD

**Issue by ShiningB** [codestation/mhtools#12]
Hello codestation, 

Is there any way to tell in wich .bins, the in-game quest files for mhp2g are located?
I found and extracted the quest descriptions, but i couldn't find or extract any .mib files.
Could you perhaps, point me in the right direction?

**Comment by codestation** [comment]
No idea, you need to check the files to find out what ones are the quest files. A module to try to decrypt every unknown file and look for a .mib pattern would be your best option.

BTW, some years ago somebody provided me a (incomplete) list of the mib files of MHP3RD, you could use this info to extrapolate to MHP2G and find the quests

> Quets 1 Village: 2820 to 2824
> Quest 2 Village: 2884 to 2901
> Quest 3 Village: 2948 to 2966
> Quest 4 Village: 3012 to 3028
> Quest 5 Village: 3076 to 3092
> Quest 6 Village: 3140 to 3153 \ (3154 & 3155) Urgent? & Special
> 
> Quest 1 GH Low Rank: 3204 to 3212
> Quest 2 GH Low Rank: 3268 to 3279
> Quest 3 GH Low Rank: 3332 to 3350
> Quest 4 GH Low Rank: 3396 to 3419
> Quest 5 GH Low Rank: 3460 to 3480 \ (3481) Urgent?
> 
> Quest 6 GH High Rank: 3524 to 3546
> Quest 7 GH High Rank: 3588 to 3622
> Quest 8 GH High Rank: 3652 to 3689 \ (3690 & 3691) Urgent?
> 
> Training Camp BASIC & WEAPON: 3716 to 3737
> Training Camp GROUP: 3780 to 3785
> 
> Quest GH Hotspring: 3844 to 3850
> Quest GH Drink: 3908 to 3927

**Comment by ShiningB** [comment]
For mhp3rd simply renaming the listed .bins to .mib did the trick, I could open them with a quest editor.
Thanks a lot for that list, it will come in handy. 

I will try the same thing for mhp2g.
Thanks again.

The same thing worked for mhp2g. I found some 450 quests. They are from 4792 to 5270.
