### ISSUE TITLE
Mass unpacking of .pak files

### ISSUE THREAD

**Issue by kenshinzv** [codestation/mhtools#13]
I'm new to using these kind of tools so I searched up on how to use your .java files
I tried going on to the directory where the MHTools.java and used 'javac MHTools.java' to compile but it seems there are errors 45 in total saying 

error: cannot find symbol
                new KirkCypher().encrypt(args[1]);

I also installed the Bouncy Castle Crypto API as said in the README, I think?
as I looked up how to install it involving pasting the .jar file into the java's ext directory and adding a line in the java.security file.
I tried compiling again, still error. What should I do? I just want to decrypt the data.bin of MHFU to take the models and import them into Blender for some animations. Knowing how to rip the models out is another thing though...

EDIT: So I got it working, decrypted the bin file, but how do I extract the models now?

EDIT2: I figured out how to extract models, but it's very tedious is there a way to unpack multiple .pak files?

**Comment by FikriRNurhidayat** [comment]
Okay, now I wonder how you can extract the models, can you tell me how?

But, I can help with mass unpacking if you use WSL or anything with POSIX compliance. Also do this on the directory you want to have the DATA.BIN extracted.

```sh
#!/bin/sh

java -jar $HOME/Downloads/mhtools.jar --dec-all ../PSP_GAME/USRDIR/DATA.BIN .
find . -name '*.pak' | xargs -I {} sh -c 'cd $(dirname {}) && java -jar $HOME/Downloads/mhtools.jar --extract $(basename {}) 6'
find . -name '*.tmh' | xargs -I {} sh -c 'cd $(dirname {}) && java -jar $HOME/Downloads/mhtools.jar --extract $(basename {}) 5'
find . -name '*.bin' | xargs -I {} sh -c 'cd $(dirname {}) && java -jar $HOME/Downloads/mhtools.jar --extract $(basename {}) 1'
```

Just change ` $HOME/Downloads/mhtools.jar` with the location of the jar file.
