### ISSUE TITLE
Using

### ISSUE THREAD

**Issue by slentara1** [codestation/mhtools#14]
I'm trying to use this file to extract some textures but no matter what i do it won't run. Am I missing something?

**Comment by codestation** [comment]
What do you mean with "it wont run"? Please paste the exact command and output you are getting.

**Comment by slentara1** [comment]
I'M AN IDIOT IS ALL LOL. I didn't realize the instructions were in the
readme. I got it to work but I couldn't use the textures I found. Thank you
for responding. Sorry for wasting your time.
