### ISSUE TITLE
Extract .pac from MHFU IOS

### ISSUE THREAD

**Issue by slentara1** [codestation/mhtools#17]
So we attempted to us mhtools.jar to decrypt an 18KB .pac file. It turned into 81 GB of files. we used the <java -jar mhtools.jar --dec> command was this wrong? Can you unpack .pac files?

**Comment by codestation** [comment]
No, this tool was only made to unpack/decrypt the MHFU/MHP3RD from PSP games. Dunno if there are modded tools to unpack the files from other platforms.
