### ISSUE TITLE
gim file

### ISSUE THREAD

**Issue by at3** [codestation/mhtools#6]
Is none.gim really gim file?

**Comment by codestation** [comment]
Probably yes but i cannot find a way to decode it. Looks like its missing the header (or maybe is shared whith another gim in the package? dunno...)

**Comment by at3** [comment]
http://att.bbs.duowan.com/forum/201305/05/163655ssxcfbxxatnancha.png
http://att.bbs.duowan.com/forum/201305/05/163656m2zamhz2445szzli.png

Is this image right?

**Comment by codestation** [comment]
Looks like a part of a wing or something. Those images are from the none.gim files? A sure way to know it to identify what monster it comes from, edit them with some distinctive mark, convert them back to gim and load it in the game to see if there are changes/doesn't crash.
