### ISSUE TITLE
Building the tools

### ISSUE THREAD

**Issue by kaubonbon** [codestation/mhtools#7]
Hi,

since I am a real java noob, all my tries to build your mhtools keep failing. This is what I have tried so far:

Executed from the dir with your extracted zip:

jar -cvf mhtools.jar src/base/_.java src/crypt/_.java src/dec/_.java src/enc/_.java src/img/_.java src/jpcsp/crypto/_.java src/keys/*.java

Running the resulting mhtools.jar with
java -jar mhtools.jar
results in:
"no main manifest attribute, in mhtools.jar" <translated>

Included the manifest file with:
jar -cvfm mhtools.jar manifest.txt src/base/_.java src/crypt/_.java src/dec/_.java src/enc/_.java src/img/_.java src/jpcsp/crypto/_.java src/keys/*.java mhtools.jar
Running it results in:
"error: main class base.MHTools could not be loaded or found" <translated>

So am I right with the assumption, that I have to first compile the *.java to *.class and then merge it to a jar, and then run it from the command line?

However, I tried to compile it with javac like that (already found out about those bcprov...jar):
javac -classpath bcprov-jdk16-146.jar src/base/_.java src/crypt/_.java src/dec/_.java src/enc/_.java src/img/_.java src/jpcsp/crypto/_.java src/keys/*.java

Result is:
I get 100 errors, with lines like that:
src\base\Decoder.java:44: error: unmappable character for encoding Cp1252
_wq·~x∟äNı½║¶=Ë«ml¥+┬[«¯&±=╠º¿a¿P;█%PÌ═7'¦y¡¼↔¿↓I¹Î9╝ln×+yª¤¤À?ö▄┐Q:A c║▓ozm§│f‼
·=ÀgÐsúSÁÛx‼×TkPòıRã═cÃzt) P­:åÂæ¹Ö[╬lu1▓âv☻¨▒Px­♀$ñ?♀↔§i       yBƒ¶E◄]w⌂¯Äh┬jú┘
:i⌂¸Û¹Î?t.»~Û÷¬tƒ>┌╠g1äRz??vò³‗+HÂ0Ô▲↔↓┴®aõN▓8╬;?

Furthermore I get exactly 90 beeps from my loudspeaker after every compilation try °o°

Please, help.

**Comment by codestation** [comment]
I added an Ant build file to the project. Just install apache-ant and execute ant in the project root (where the build.xml is located). Ant will build the class files and create the jar for you.

**Comment by kaubonbon** [comment]
Your Ant script creates the same error as the manual build process.
When building without "bcprov-jdk16-146.jar" I get errors like this:

```
[javac] C:\...\mhtools-master\src\jpcsp\crypto\AES128.java:29: error: package org.bouncycastle.jce.provider does not exist
[javac] import org.bouncycastle.jce.provider.BouncyCastleProvider;
```

and like this:

```
[javac] C:\...\mhtools-master\src\jpcsp\crypto\ECDSA.java:80: error: cannot find symbol
[javac]         ECPrivateKeySpec privateKeySpec = new ECPrivateKeySpec(new BigInteger(priv), spec);
[javac]                                               ^
[javac]   symbol:   class ECPrivateKeySpec
[javac]   location: class ECDSA
```

When I put the contents of bcprov...jar into the src dir, I get the same errors like mentioned in my last post.
Including the beeps :-)

**Comment by kaubonbon** [comment]
Ok? It worked now, I don't know what it was. I thought I just moved the bcprov...jar from src to root-dir, but I cannot reproduce it. Anyways... thank you!
