### ISSUE TITLE
Short question

### ISSUE THREAD

**Issue by irregular9** [codestation/mhtools#8]
Hello, when I extract the MHP3RD_DATA.bin from the translation patch... the mhtools tries to extract a 3.5 TB 00.bin file... is that really normal or.. I'm just doing every thing wrong?

**Comment by irregular9** [comment]
Ok, i just exracted everything from the data.bin, and figured out how to extract the tables from 0017.bin, where the most important things are, but I really need to know how to extract the other files, 2813-2818.bin and 3972-3986.bin. It just extracts an "enddata.bin and a filelist.txt" nothing else.

**Comment by codestation** [comment]
I just tried with mine and extracted the files just fine:

```
java -jar mhtools.jar --extract 2813.bin 1
```

```
java -jar mhtools.jar --extract 3973.bin 4
```

Whats the output from the tool when you try to extract those files?

**Comment by irregular9** [comment]
java.exe -jar mhtools.jar --extract Out/02/2813.bin 1

I've got everything extracted in the same directory, in a folder named "Out". The thing is that 2813 extract only an enddata.bin and the filelist.txt, but, the 3973 doesnt extract anything at all. Im using this command:

java -jar mhtools.jar --extract Out/03/3973.bin 4

But... I think the problem is because I'm using the already translated ps3 files, I will try with a clean ISO.

**Comment by irregular9** [comment]
Yeah, it was because of the ps3 version, I'm working on the psp version now and it works just fine, do you know why the ps3 version, although is virtually the same, is.... different? I mean, the 0017.bin can be extracted just fine, but rest fails.

**Comment by codestation** [comment]
For example, have you confirmed that the 3973 on PSP is the same as the PS3? If they added/removed conent then the original 3973 could be located with another filename on the PS3 version.

Also i never tested this tool with the PS3 files so IDK if it works or not (i don't have a PS3).

**Comment by irregular9** [comment]
You're right, it seems there is more content and in some point, the files are different, just one more question and nothing else. Is there a way to extract a group of .bin files in one step? or.. do I really have to try every one of them one by one? hahaha
