### ISSUE TITLE
Short question

### ISSUE THREAD

**Issue by at3** [codestation/mhtools#9]
--encrypt-kirk 

Does this function normally?

**Comment by codestation** [comment]
No, the encrypt function from jpcsp was bugged when I grabbed that code. I
assume that their code works now but sadly their code layout changed a lot
in those years so I cannot simply grab the updated class. Fell free to
contribute a patch or use sed-pc to encrypt it back using the MH savedata
key.

printf("Tell your world\n");

**Comment by at3** [comment]
http://wololo.net/downloads/index.php/download/8122

sed -e MHP3RD.BIN PARAM.SFO OUT.BIN ULJM05800.bin
Program exited with code : -2000

ULJM05800.bin 
E3 05 CE FA EB 46 B0 31 85 9A 27 5B DF 32 D8 63

Where is wrong?

**Comment by codestation** [comment]
The output file must be named MHP3RD.BIN, so rename the input file to
something else. Sed-pc error messages are confusing.

**Comment by at3** [comment]
I was able to do it.
Thank you, codestation.
